### ISSUE TITLE
Create a list of existing tutorial and demo notebooks

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/DMStackClub#1]
We would like to collect a list of existing tutorial resources. We expect this will largely draw from Robert's tutorials.

**Comment by drphilmarshall** [comment]
@Madejski was up for starting a Google doc for this, that we can all help work up and then sit back and stare at. BTW I think Robert's notebooks are best characterised as _demos_, rather than tutorials: a example of a Stack Club project would be to take one of his demos, and turn it into a tutorial that meets our requirements.

**Comment by drphilmarshall** [comment]
OK, here's a [Google doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit?usp=sharing) for us to make our complete list, and then distill from it a set of "seed notebooks." When we have the listing section done, we can close this out - and when we have the seeds indentified, we can close #2 as well! Over to you, Greg.

**Comment by drphilmarshall** [comment]
@yoachim @danielsf:  Hope all's well with you both! I'm collecting DM stack demo and tutorial notebooks to act as seeds for a community documentation drive known as "DM Stack Club", and @rhiannonlynne mentioned you might have some good links for us to follow. So far I've got Robert L's demos, the DM team tutorial, and the SQuARE team tutorial. Know of any other good jupyter notebooks we could build on? Feel free to just drop the URL in a reply, or add them to [this doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit?usp=sharing) if you're feeling especially energetic :-) Thanks!

**Comment by drphilmarshall** [comment]
Hi @cwwalter! I'm collecting demo and tutorial notebooks showing how to use the LSST DM Stack - didn't you make some of these a while back? If you know of any other good resources of this kind, I'd love to hear of them. So far I've got Robert L's demos, the DM team tutorial, and the SQuARE team tutorial. This is for a community documentation drive known as "DM Stack Club", which is cranking into gear and should be fun. Thanks!

**Comment by SimonKrughoff** [comment]
The commissioning team are currently building an agenda for an upcoming bootcamp.  The way it's looking, the agenda will be focused on the more functional aspects of the DM ecosystem.  I think notebook tutorials coming out of that may be very useful for this team.

**Comment by cwwalter** [comment]
Hi @drphilmarshall.

There are two sets I have worked on.  The first, which were done with Simon and others, were recently redone at the sprint week for dealing with DC1 data.  Alex and Javier redid and validated them.

https://github.com/LSSTDESC/SSim_DC1/tree/master/Notebooks

Then there is the set of notebooks/tutorials I made about how to write pipetasks and do low-level DM processing:

https://github.com/LSSTDESC/DataManagementWorkbook
http://lsstdesc.github.io/DataManagementWorkbook/

The cover basic AFW, tables and catalogs and command line tasks.  But they are old.  I did these when I was getting started to understand how things work and probably a fair amount is out of date now.

**Comment by drphilmarshall** [comment]
Thanks very much, Chris! We'll take a look, and see whether we can re-use
anything. I don't see a LICENSE file in either repo, would you mind letting
us know which one you one day plan to add? Thanks!

**Comment by cwwalter** [comment]
> Thanks very much, Chris! We'll take a look, and see whether we can re-use
> anything. I don't see a LICENSE file in either repo, would you mind letting
> us know which one you one day plan to add? Thanks!

Well... If I had to choose personally I would choose the GPL but I know this isn't popular among some people in DESC for various reasons.  But, I had no particular intention on adding a license on these so I'm happy for you to add whatever license you prefer if they are incorporated somewhere.

I think the tutorial I wrote on pipeline tasks is pretty unique so if it isn't too out of date it is probably worthwhile to capture that information.

**Comment by drphilmarshall** [comment]
Great, thanks @cwwalter ! We'll look out for the pipeline tasks tutorial in particular. Thanks for sharing :-)

@Madejski can you take a good look through Chris' notebooks and add them to the listing in the Seed Notebooks doc, please? When you think you have a complete listing, feel free to close this out - if we come across more notebooks we can always add them later.

**Comment by drphilmarshall** [comment]
We looked at our "complete listing" last week, and deemed it extensive enough to start planning how to connect the notebooks we have with the topics we want to cover - I'll issue that separately. Thanks all!
