### ISSUE TITLE
First DM Stack tutorial notebook

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#18]
Make a first tutorial notebook to exercise DM Stack (and hence check that people are set up correctly). This could be “Hello Sky” (#13 ) or something else - perhaps one of the v15 HTML tutorials? Assigning to Alex, who wanted to write a notebook :-) Belongs to epic #15

**Comment by kadrlica** [comment]
The "first notebook" desire was satisfied through lsst-sqre/notebook-demo#2. I think this could be closed, though we need to decide how to share tutorials across the groups.
