### ISSUE TITLE
Define the scope of tutorial subjects

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/DMStackClub#2]
We would like to define the set of subjects that we want to cover with tutorials.

**Comment by drphilmarshall** [comment]
Definitely: I have been thinking about this as the Stack Club "syllabus". We can get a good start on this by listing the available demos (#1), and then grouping them - but free-form suggestions will always be welcome! When we have a doc for the demo list, let's add a section called Syllabus and put suggestions there. I know @jonathansick is interested in thinking about this - he's bound to have good ideas. And of course the commissioning team will have a key set of tasks in mind that they want to have tutorials that cover.

**Comment by drphilmarshall** [comment]
[Here's the doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit?usp=sharing):  while emailing the group I decided a set of "seed" notebooks was more helpful terminology than a "syllabus" - because we are growing things, not teaching things, here.

**Comment by kadrlica** [comment]
List is under construction on the above mentioned google doc.

**Comment by kadrlica** [comment]
List has been constructed [here](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#heading=h.5oju3qvynhh). Please edit/comment in google doc.
