### ISSUE TITLE
Commissioning team's list of existing tutorials and resources

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#27]
Hi @bechtol ! Last week you mentioned that the commissioning team has a list of existing tutorials and resources - I'd like to merge that into the Stack Club document [here](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#), please. Would you mind sharing a link, or [pasting raw text into the document](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#) for @Madejski to process? Thanks!

**Comment by drphilmarshall** [comment]
PS. I think this will also satisfy a second action we wrote down last week, namely to _"capture links to "tour" documents that also explain data products, algorithms, and philosophy of pipelines."_ Both these belong to epic #23

**Comment by bechtol** [comment]
I added several references for overall organization of the Stack immediately after our last meeting in [Section 8 of the google doc](https://docs.google.com/document/d/1PSA1uWwTfs9CweatpxF8CEPGBYRY5ZaXB39JzXYE7_U/edit#heading=h.x8epfbu6vrak)

**Comment by drphilmarshall** [comment]
For future reference, the commissioning team's notebooks are under development at https://github.com/lsst-com/notebooks - a good repo to watch!
