### ISSUE TITLE
Potential Phase 1 Participants

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#28]
@rhiannonlynne @brantr @aprajita Let's try to identify a few people from each science collaboration who might like to start following the DM Stack Club, and potentially be involved in Phase 1 (turning the seed tutorials into community notebooks, by the August PCW). 

We said that we would focus on either people who had some familiarity with the DM stack already, or were extra specially motivated to start learning the Stack - as well as being available to meet fortnightly from May 24 onwards. Don't worry if you can't think of anyone from your science collaboration - you can also encourage participation in Phase 2 (from August onwards) closer to the time. And it doesn't matter if people come to the channel but can't make it to the sessions - at least they'll be able to follow the Club's progress, and chime in from time to time.

We'll assemble in the [#dm-stack-club Slack channel](https://lsstc.slack.com/messages/C9YRAS4HM/) as our primary meeting point. 
I'll ask some DESC people to join that channel, great if you can do the same! I'll also flag this issue to the other science collaboration chairs, to try to cover all our bases. Thanks!

**Comment by brantr** [comment]
I've invited a handful of people from Galaxies who I think might be interested.  I'll update once I hear back.

**Comment by rhiannonlynne** [comment]
I asked Wes Fraser from the Solar System group, I didn't have a long list of people who hit those qualifications :)  I haven't heard anything back yet. 

I'm thinking that the most interesting thing from a solar system point of view related to the DM stack directly, might be taking some images with known solar system objects (in particular an active object) and looking at the photometry. Perhaps plugging in various types of photometry measurements. What is the plan as far as input data?

**Comment by drphilmarshall** [comment]
@rhiannonlynne The HSC data might be the most interesting for solar system investigation, but let's discuss that elsewhere - and I'll try to catch up with Wes again later in the summer (he didn't quite seem to have the bandwidth to take part in phase 1). 

The phase 1 projects are getting started, with #50 a good place to catch up with who is active and what they are thinking of working on. Closing this out!
