### ISSUE TITLE
DM Stack Club breakout session at LSST 2018, August 13-17, Tucson

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#30]
@LSSTScienceCollaborations/stack-club-organizers 

[Registration is now open](https://project.lsst.org/meetings/lsst2018/registration) for the LSST 2018 Project and Community Workshop in Tucson in August. I'm going to register and then submit a proposal for a DM Stack Club breakout session. By then we plan to have our tray of seedling notebooks all lined up and ready for people to work though, so a good session might look like the draft below - what do you think? Anything missing, or could be said better?

### DM Stack Club
Come and learn the DM Stack by working your way through one of our community-built tutorial jupyter notebooks, and then extending it to do the things you are most interested in. We'll provide access to a jupyterlab instance, so no installation will be required: you can just jump in. We'll give you a quick guided tour of the tutorials we've got, and a demonstration of one of them in action. Then, we'll break up into a short hack session. The DM Stack Club is an LSSTC-supported initiative that will keep going by video through the Fall: you can get started in Tucson at the PCW, and then carry on learning with us when you get home.

**Comment by brantr** [comment]
Great, thanks for submitting this. I am planning to attend PCW and any DM Stack Club session.

My only suggestions:

Point to https://github.com/LSSTScienceCollaborations/DMStackClub <https://github.com/LSSTScienceCollaborations/DMStackClub> in the abstract?

Write out LSST Data Management (DM) Stack Club in the title or abstract?  

Thanks again Phil.

-Brant

**Comment by drphilmarshall** [comment]
Alright, I submitted our proposed session: https://project.lsst.org/meetings/lsst2018/content/dm-stack-club  @jonathansick @womullan @SimonKrughoff I took the liberty of listing you all as "vital attendees" but of course will understand if unavoidable clashes mean you have to be elsewhere.
