### ISSUE TITLE
JupyterLab instructions are incomplete

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/DMStackClub#32]
I am planning to flesh this out to make it accessible to a newbie.

**Comment by drphilmarshall** [comment]
Hey @Madejski It looks like we're making the jump to jupyterlab at NCSA, so let's document that as part of PR #33. I'll make a start, renaming the notes file and adding pointers to the relevant LSST technote, and ping you when I am done.

**Comment by Madejski** [comment]
Hey @drphilmarshall - that sounds good.  I think I know why we were getting the "raw" vs. "markdown" issues - I might have been running different versions of python at different times...  thanks for all your help earlier today!  --G

**Comment by Madejski** [comment]
I think I resolved the problem of "Markdown" vs "Raw."  Thanks!  --Greg
