### ISSUE TITLE
Phase 1 DM Stack Club Session, Wednesday June 6, 1000 PDT

### ISSUE THREAD

**Issue by kadrlica** [LSSTScienceCollaborations/DMStackClub#44]
Hi @LSSTScienceCollaborations/dm-stack-club !

We'll have our next club session this Wednesday, starting 1000 PDT, on Zoom, meeting ID 946390572. We'll be getting a walkthrough of some of the notebooks that got started at the commissioning bootcamp from @bechtol. If you want to get a head start on this weeks session, you can find the commissioning notebooks at: https://github.com/lsst-com/notebooks

Comments and/or questions welcome, either here or on Slack! See you Friday,

Phil, Greg & Alex

**Comment by kadrlica** [comment]
Some minutes are posted on the google doc. @drphilmarshall is the recording of the meeting available somewhere?

**Comment by drphilmarshall** [comment]
I just posted the link to the June 6 session video to the [meetings page](https://github.com/LSSTScienceCollaborations/DMStackClub/blob/master/Meetings.md). Thanks for hosting!
