### ISSUE TITLE
Broken link in DMStackClub/GettingStarted/Readme.md

### ISSUE THREAD

**Issue by brantr** [LSSTScienceCollaborations/DMStackClub#68]
The [Readme.md](https://github.com/LSSTScienceCollaborations/DMStackClub/tree/master/GettingStarted) in GettingStarted links to [Hello_World.ipynb](https://github.com/LSSTScienceCollaborations/DMStackClub/blob/master/notebooks/Hello_World.ipynb) but that page doesn't exist?  I get a 404 error.

**Comment by jtmyles** [comment]
I've created a pull request (#69) fixing the link. This is my first pull request. If I've done something that's wrong or breaking protocol please let me know.
