### ISSUE TITLE
Computing model

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#7]
@SimonKrughoff Thanks for starting the computing model document, [here](https://docs.google.com/document/d/1TVRWTg1en4yXJ6ZbBEfmvVk77MnRSgXpQGaOkZIRyhw/edit#). I added a second section that describes what we are actually going to do, and am hoping you can help me fill it out. Basically we're after the cheapest possible solution to stretch our LSSTC funds as far as we can: can you please make us a proposal (by editing this doc) so we can see whether we can live with it? Thanks!

**Comment by SimonKrughoff** [comment]
@drphilmarshall have a look at my updated text.  The big thing is that I think we must have some persistent storage in both the user space and a shared space.  We need to cost that out.
