### ISSUE TITLE
Set up and Test the Stack Club Cluster

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTScienceCollaborations/DMStackClub#9]
@SimonKrughoff @womullan 

Very soon after writing down the computing model (#7), I think we will need a few of us to be trying (and failing) to do stuff on the same Stack Club Cluster that we'll be using in a couple of months in the club sessions. Once the plan is in place, could you help us set up a minimal-cost cluster so that at least @kadrlica , @Madejski and I can start experimenting, please? I am sincerely hoping that it will be pretty straightforward to set something up that is very similar to what you use for the DM team tutorials and for the Commissioning Team's notebook-writing sessions. What do you think? 

- [ ] @drphilmarshall explore options for domain names.  
- [ ] @drphilmarshall make sure billing model for cloud services is understood.

**Comment by SimonKrughoff** [comment]
This is certainly possible.  I think the first thing to do is to set up a Google organization that has the proper billing and has permissions to spin up GKE clusters.

I'm not exactly sure how to do that, but will look into it.

**Comment by SimonKrughoff** [comment]
I believe it will require following the instructions here: https://cloud.google.com/resource-manager/docs/quickstart-organizations

**Comment by SimonKrughoff** [comment]
We will also need to procure a domain name for the service and a legitimate cert for it ([Let's Encrypt](https://letsencrypt.org) gives free certs).

**Comment by drphilmarshall** [comment]
I am confused. I understood piggy-backing off the DM team's tutorial cluster would be a lot simpler than this! @womullan ? For example, the "billing model" we have is to direct all our LSSTC funds to Wil, to cover the required extension in scope. Is this not the right model for us?

**Comment by drphilmarshall** [comment]
OK, after some offline discussion, @SimonKrughoff has set up a team of admins and a team of users  (actually, two GitHub organizations) that we can use to grant access to the tutorial cluster, and @kadrlica and I are experimenting with it. Simon has been keeping a few notes in a Computing Model document [here](https://docs.google.com/document/d/1TVRWTg1en4yXJ6ZbBEfmvVk77MnRSgXpQGaOkZIRyhw/edit#). Thanks Simon!
